import type { Category, PlaceStatus, PriceLevel, Profile } from '@/types/models'

/** Пароль сидовых учёток локального бэкенда. Боевого входа не касается. */
export const LOCAL_PASSWORD = 'demo1234'

// Имена — заглушки: на боевом бэкенде они приходят из `profiles.display_name`,
// который задаётся при заведении аккаунта в дашборде Supabase.
export const SEED_PROFILES: (Profile & { email: string })[] = [
  { id: 'u-stas', email: 'stas@example.com', displayName: 'Стас', avatarUrl: null },
  { id: 'u-alina', email: 'alina@example.com', displayName: 'Алина', avatarUrl: null },
]

/** Тот же справочник, что заводит `0001_init.sql`, раздел 3. */
export const SEED_CATEGORIES: Category[] = [
  { id: 'c-cafe', name: 'Кафе', emoji: '☕', sortOrder: 10 },
  { id: 'c-rest', name: 'Ресторан', emoji: '🍽', sortOrder: 20 },
  { id: 'c-bar', name: 'Бар', emoji: '🍸', sortOrder: 30 },
  { id: 'c-park', name: 'Парк', emoji: '🌳', sortOrder: 40 },
  { id: 'c-museum', name: 'Музей', emoji: '🏛', sortOrder: 50 },
  { id: 'c-activity', name: 'Активность', emoji: '🎯', sortOrder: 60 },
  { id: 'c-nature', name: 'Природа', emoji: '⛰', sortOrder: 70 },
  { id: 'c-event', name: 'Событие', emoji: '🎪', sortOrder: 80 },
  { id: 'c-other', name: 'Другое', emoji: '📍', sortOrder: 90 },
]

interface SeedPlace {
  id: string
  title: string
  categoryId: string
  status: PlaceStatus
  price: PriceLevel
  address: string
  lat: number
  lng: number
  description: string
  sourceTitle: string
  authorId: string
  daysAgo: number
  rating: number | null
}

/** Места из прототипа — реальные адреса Петербурга с настоящими координатами. */
export const SEED_PLACES: SeedPlace[] = [
  {
    id: 'p1',
    title: 'The Бык',
    categoryId: 'c-rest',
    status: 'want',
    price: 'high',
    address: 'ул. Некрасова, 7',
    lat: 59.9385,
    lng: 30.3556,
    description:
      'Нашли в видосе: маленький зал, открытая кухня, стейк рибай за 990. Говорят, надо бронировать за неделю — иначе стоять у бара.',
    sourceTitle: '«Стейки за 900 в центре Питера» · TikTok',
    authorId: 'u-alina',
    daysAgo: 19,
    rating: null,
  },
  {
    id: 'p2',
    title: 'Город 812',
    categoryId: 'c-bar',
    status: 'visited',
    price: 'medium',
    address: 'наб. канала Грибоедова, 22',
    lat: 59.9345,
    lng: 30.3238,
    description: 'Шумно, тесно, но настойки правда хорошие. Пришли в девять — сели только в одиннадцать.',
    sourceTitle: '«Бары канала Грибоедова» · YouTube',
    authorId: 'u-stas',
    daysAgo: 150,
    rating: 4.25,
  },
  {
    id: 'p3',
    title: 'Кофейня миньонов',
    categoryId: 'c-cafe',
    status: 'visited',
    price: 'low',
    address: 'Гороховая ул., 41',
    lat: 59.9294,
    lng: 30.3181,
    description: 'Наше место на дождь. Раф с халвой, два кресла у окна, никто не гонит.',
    sourceTitle: '«Кофе до 200₽ в центре» · Reels',
    authorId: 'u-alina',
    daysAgo: 163,
    rating: 4.5,
  },
  {
    id: 'p4',
    title: 'Сапы с подсветкой',
    categoryId: 'c-activity',
    status: 'want',
    price: 'medium',
    address: 'Крестовский остров',
    lat: 59.9714,
    lng: 30.2456,
    description: 'Ночной заплыв с подсветкой досок. Стартуют в 22:00, длится два часа. Нужен купальник и сменка.',
    sourceTitle: '«Ночной сап по Неве» · TikTok',
    authorId: 'u-stas',
    daysAgo: 29,
    rating: null,
  },
  {
    id: 'p5',
    title: 'Музей МАФ',
    categoryId: 'c-museum',
    status: 'want',
    price: 'low',
    address: 'ул. Смольного, 4',
    lat: 59.9469,
    lng: 30.3949,
    description: 'Маленький музей, куда никто не ходит. Идеально на дождливую субботу.',
    sourceTitle: '«Странные музеи Питера» · YouTube',
    authorId: 'u-alina',
    daysAgo: 52,
    rating: null,
  },
  {
    id: 'p6',
    title: 'Севкабель Порт',
    categoryId: 'c-park',
    status: 'visited',
    price: 'low',
    address: 'Кожевенная линия, 40',
    lat: 59.9269,
    lng: 30.2408,
    description: 'Пришли к закату, съели по хот-догу, сидели на бетоне у воды. Лучший вечер весны.',
    sourceTitle: '«Закат на Севкабеле» · Reels',
    authorId: 'u-stas',
    daysAgo: 81,
    rating: 4.75,
  },
  {
    id: 'p7',
    title: 'Новая Голландия',
    categoryId: 'c-park',
    status: 'want',
    price: 'low',
    address: 'наб. Адмиралтейского канала, 2',
    lat: 59.9289,
    lng: 30.2891,
    description: 'Взять плед и кофе, лечь на газон. Летом там кино по четвергам.',
    sourceTitle: '«Пикник в Новой Голландии» · Reels',
    authorId: 'u-alina',
    daysAgo: 40,
    rating: null,
  },
  {
    id: 'p8',
    title: 'Бар «Юность»',
    categoryId: 'c-bar',
    status: 'want',
    price: 'medium',
    address: 'Литейный пр., 33',
    lat: 59.9403,
    lng: 30.3486,
    description: 'Маленький бар с виниловым проигрывателем. Обещают лучший негрони в районе.',
    sourceTitle: '«Куда пойти в четверг» · TikTok',
    authorId: 'u-stas',
    daysAgo: 26,
    rating: null,
  },
  {
    id: 'p9',
    title: 'Кронштадт на день',
    categoryId: 'c-nature',
    status: 'want',
    price: 'medium',
    address: 'Кронштадт',
    lat: 59.9967,
    lng: 29.7681,
    description: 'Форты, парк «Остров фортов», обратно на метеоре. День уходит целиком.',
    sourceTitle: '«Кронштадт за один день» · YouTube',
    authorId: 'u-alina',
    daysAgo: 17,
    rating: null,
  },
  {
    id: 'p10',
    title: 'Панорама «Небо»',
    categoryId: 'c-other',
    status: 'rejected',
    price: 'high',
    address: 'Лахтинский пр., 2',
    lat: 59.9871,
    lng: 30.1779,
    description: 'Очередь сорок минут, стекло грязное, вид так себе. Больше не идём.',
    sourceTitle: '«Смотровые Питера» · Reels',
    authorId: 'u-stas',
    daysAgo: 94,
    rating: 2.75,
  },
  {
    id: 'p11',
    title: 'Больше кофе',
    categoryId: 'c-cafe',
    status: 'want',
    price: 'low',
    address: 'ул. Рубинштейна, 15',
    lat: 59.9296,
    lng: 30.3446,
    description: 'Окно выдачи и три табуретки. Говорят, лучший фильтр в районе — берём с собой и идём гулять.',
    sourceTitle: '«Кофе на Рубинштейна» · Reels',
    authorId: 'u-alina',
    daysAgo: 13,
    rating: null,
  },
  {
    id: 'p12',
    title: 'Ботанический сад',
    categoryId: 'c-nature',
    status: 'want',
    price: 'medium',
    address: 'ул. Профессора Попова, 2',
    lat: 59.9714,
    lng: 30.3231,
    description: 'Тропическая оранжерея зимой — единственное место в городе, где пахнет летом.',
    sourceTitle: '«Оранжереи Петербурга» · YouTube',
    authorId: 'u-stas',
    daysAgo: 11,
    rating: null,
  },
  {
    id: 'p13',
    title: 'El Copitas',
    categoryId: 'c-bar',
    status: 'want',
    price: 'high',
    address: 'адрес по брони',
    lat: 59.9227,
    lng: 30.3196,
    description: 'Бар по записи, адрес присылают в день визита. Сет из шести коктейлей, длится часа три.',
    sourceTitle: '«Спикизи Питера» · TikTok',
    authorId: 'u-alina',
    daysAgo: 9,
    rating: null,
  },
  {
    id: 'p14',
    title: 'Пышечная на Желябова',
    categoryId: 'c-cafe',
    status: 'visited',
    price: 'low',
    address: 'Большая Конюшенная, 25',
    lat: 59.9375,
    lng: 30.3243,
    description: 'Пять пышек, кофе с молоком из бака, липкий стол. Ничего не меняется, и слава богу.',
    sourceTitle: '«Пышки с 1958 года» · Reels',
    authorId: 'u-stas',
    daysAgo: 203,
    rating: 4.75,
  },
  {
    id: 'p15',
    title: 'Каток в Новой Голландии',
    categoryId: 'c-activity',
    status: 'want',
    price: 'medium',
    address: 'наб. Адмиралтейского канала, 2',
    lat: 59.9291,
    lng: 30.2887,
    description: 'Зимой заливают каток с гирляндами. Прокат на месте, вечером играет музыка.',
    sourceTitle: '«Катки Петербурга» · YouTube',
    authorId: 'u-alina',
    daysAgo: 7,
    rating: null,
  },
  {
    id: 'p16',
    title: 'Экскурсия по Ленфильму',
    categoryId: 'c-museum',
    status: 'want',
    price: 'medium',
    address: 'Каменноостровский пр., 10',
    lat: 59.9573,
    lng: 30.3183,
    description: 'Пускают в павильоны и костюмерную. Только по записи, группы по двенадцать человек.',
    sourceTitle: '«Внутри Ленфильма» · TikTok',
    authorId: 'u-stas',
    daysAgo: 5,
    rating: null,
  },
  {
    id: 'p17',
    title: 'Пляж на Заячьем острове',
    categoryId: 'c-park',
    status: 'want',
    price: 'free',
    address: 'Петропавловская крепость',
    lat: 59.9503,
    lng: 30.3164,
    description: 'Песок, вода и стена крепости за спиной. Купаться нельзя, сидеть с кофе — можно.',
    sourceTitle: '«Питерские пляжи» · Reels',
    authorId: 'u-alina',
    daysAgo: 3,
    rating: null,
  },
  {
    id: 'p18',
    title: 'Ферма в Токсово',
    categoryId: 'c-nature',
    status: 'want',
    price: 'medium',
    address: 'Токсово, Ленобласть',
    lat: 60.1533,
    lng: 30.5147,
    description: 'Зубры, козы и домик с печкой. Ехать час на электричке, обратно последняя в 21:40.',
    sourceTitle: '«Куда выехать из Питера» · YouTube',
    authorId: 'u-stas',
    daysAgo: 2,
    rating: null,
  },
  {
    id: 'p19',
    title: 'Книжный «Подписные издания»',
    categoryId: 'c-cafe',
    status: 'visited',
    price: 'medium',
    address: 'Литейный пр., 57',
    lat: 59.9377,
    lng: 30.3479,
    description: 'Кофе на втором этаже и полтора часа между полками. Уходим всегда с двумя книгами.',
    sourceTitle: '«Книжные Петербурга» · Reels',
    authorId: 'u-alina',
    daysAgo: 108,
    rating: 4.5,
  },
]

/** Отзывы к посещённым местам. Ровно по одному от каждого — как требует О-1. */
export const SEED_REVIEWS: {
  id: string
  placeId: string
  authorId: string
  rating: number
  text: string
  daysAgo: number
}[] = [
  { id: 'r1', placeId: 'p2', authorId: 'u-alina', rating: 4, text: 'Настойка на облепихе — топ. Но очень громко, я устала к полуночи.', daysAgo: 150 },
  { id: 'r2', placeId: 'p2', authorId: 'u-stas', rating: 5, text: 'Ждали столик два часа. За эти деньги можно лучше — пойдём пораньше.', daysAgo: 150 },
  { id: 'r3', placeId: 'p3', authorId: 'u-alina', rating: 5, text: 'Тут мы просидели три часа и никто слова не сказал. Люблю.', daysAgo: 163 },
  { id: 'r4', placeId: 'p3', authorId: 'u-stas', rating: 4, text: 'Кофе отличный, эклер средний. Но идём сюда каждый раз.', daysAgo: 163 },
  { id: 'r5', placeId: 'p6', authorId: 'u-alina', rating: 5, text: 'Тот самый закат. Хочу так каждую пятницу.', daysAgo: 81 },
  { id: 'r6', placeId: 'p6', authorId: 'u-stas', rating: 4, text: 'Ветрено, бери куртку. В остальном идеально.', daysAgo: 81 },
  { id: 'r7', placeId: 'p10', authorId: 'u-alina', rating: 2, text: 'Дорого и толпа. Лучше просто на крышу к друзьям.', daysAgo: 94 },
  { id: 'r8', placeId: 'p10', authorId: 'u-stas', rating: 3, text: 'Вид ок, всё остальное — нет. Очередь сорок минут.', daysAgo: 94 },
  { id: 'r9', placeId: 'p14', authorId: 'u-stas', rating: 5, text: 'Пять пышек на двоих и кофе из бака. Ничего не изменилось с детства.', daysAgo: 203 },
  { id: 'r10', placeId: 'p14', authorId: 'u-alina', rating: 4, text: 'Очередь на улице в минус десять — но внутри тепло и сладко.', daysAgo: 203 },
  { id: 'r11', placeId: 'p19', authorId: 'u-alina', rating: 5, text: 'Ушли с двумя книгами и планом вернуться в мае. Кофе наверху отличный.', daysAgo: 108 },
  { id: 'r12', placeId: 'p19', authorId: 'u-stas', rating: 4, text: 'Людно в выходные. Приходить лучше к открытию.', daysAgo: 108 },
]

/** Идеи — места без адреса (М-7). */
export const SEED_IDEAS: { id: string; title: string; authorId: string; daysAgo: number }[] = [
  { id: 'i1', title: 'Снять дачу на выходные зимой', authorId: 'u-stas', daysAgo: 21 },
  { id: 'i2', title: 'Прокатиться на речном трамвайчике в белую ночь', authorId: 'u-alina', daysAgo: 15 },
  { id: 'i3', title: 'Сварить пасту с нуля дома', authorId: 'u-alina', daysAgo: 8 },
  { id: 'i4', title: 'Сходить в баню с вениками', authorId: 'u-stas', daysAgo: 4 },
]
